### ISSUE TITLE
Html incorrectly rendered in summary on job page

### ISSUE THREAD

**Issue by vivelys** [jenkinsci/git-changelog-plugin#11]
Hello,
I used the same template for both printing a summary on job page and create file (the one found here).
The file is created but when I open the job page, all html tag are visible and no rendering is done.
If I add to the a description using html tag, the description is rightly rendered.
![7b37c364-0f55-11e7-842a-87a5757184d4](https://cloud.githubusercontent.com/assets/10617428/24448068/3e4b0d58-1473-11e7-8e7c-e47ca39b038c.png)

Any idea ?
Thank you

**Comment by tomasbjerre** [comment]
Releaseing 1.48 now. Will be available within a few hours. Should fix the problem.
