### ISSUE TITLE
JIRA updator

### ISSUE THREAD

**Issue by ivkim** [jenkinsci/git-changelog-plugin#12]
I've found this to be more accurate in terms of changes between successful builds.  I've been using the update relevant JIRA issues plugin but when there are aborts/failures, Jenkins seems to lose track of the changes that would have been.  Can I request an enhancement to also update the relevant JIRA tickets? (https://wiki.jenkins.io/display/JENKINS/JIRA+Plugin)

**Comment by paulwellnerbou** [comment]
Sure you can, although I don't think this will happen in near future. This plugin is currently completely independent from Jira, so to build this, we would need to implement the Jira API, with settings for the URL, credentials, and so on.

How do you want your Jira tickets to be updated? A workflow transition?

**Comment by ivkim** [comment]
A workflow transition would be nice but that might depend on cooperation with the JIRA admin and possibly affecting other projects etc.  The Jenkins issue updater plugin basically "stamps" the ticket with a comment saying successfully built with job xyz, (or abort or failure etc).
