### ISSUE TITLE
How to use this in scripted pipelines?

### ISSUE THREAD

**Issue by jonasv** [jenkinsci/git-changelog-plugin#14]
Hey,

thanks for closing my previous ticket so fast ;)

Could you please share examples how to use this plugin and specific features (like publish jira) when using scripted pipelines? You previously said it is possible, but I can't find example anywhere. Using DSL in my case is not possible for some reason, so scripted pipelines is the only option.

Thank you

**Comment by jonasv** [comment]
Nevermind, I've your reply mentioning that description is explained in $server/pipeline-syntax/html , this is cool, unfortunately it wasn't only me who was looking for this link, why not put this link somewhere in docs ? 

You can close this, thanks.

**Comment by tomasbjerre** [comment]
If you have an example pipeline I'd be happy to add it to the readme and the wiki =)
