### ISSUE TITLE
Plugin holding open files? Unable to delete windows workspace due to busy git pack file

### ISSUE THREAD

**Issue by VermaGa** [jenkinsci/git-changelog-plugin#15]
I get the error Unable to delete windows workspace due to busy git pack file after I build and use the Git changelog plugin.

seems this was reported before as well against jenkins.
https://issues.jenkins-ci.org/browse/JENKINS-19994

**Comment by tomasbjerre** [comment]
This plugin does not use the `Git Plugin`. So the referenced jira is probably not related.

I'll have a look later here to make sure nothing obvious is locked...

**Comment by tomasbjerre** [comment]
This plugin uses a library and reads the git repository here:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/git/GitRepo.java#L82

It is closed here:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/api/GitChangelogApi.java#L76

I don't think there is much for me to do here without any more indication that it is this plugin causing it.

**Comment by tomasbjerre** [comment]
Possibly fixed by: https://github.com/tomasbjerre/git-changelog-lib/commit/9f7c782dc9be919d0ef3f59868b94130cd8a5371#diff-867ccdc6b018ef1308b3fbca701a36a6R87
