### ISSUE TITLE
Pipeline/Job DSL configuration is confusing

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/git-changelog-plugin#18]
The current configuration parameters are very hard to understand. What they do and how to use them...

For example. Should be possible to group some things into configuration objects where common parameters are stored for:
* Creating a file
* Printing on summary page
* Publishing in MediaWiki
* ...

There are also some unnecessary booleans like:
* useGitLab - If gitlab is configured, use it!
* useJiraUsernamePasswordCredentialsId - If there are supplied credentials, use them!
* ...

Perhaps it can be implemented as a new attribute in `GitChangelogRecorder`. The current `config` can be deprecated and we can create a new `changelogConfig` with a better structure.

**Comment by tomasbjerre** [comment]
@casz If you have any suggestions here, I'll listen =)

**Comment by jetersen** [comment]
@tomasbjerre I would start by adding symbols 👍 and making the config describable 👍 then perhaps split the config into groups as you suggested and provide a better step generator experience to help with the configurations experience.

describable makes it easier to create easily maintainable jelly templates that provide a better step generator.

**Comment by tomasbjerre** [comment]
Note to self: Implement custom steps, examples available here: https://github.com/jenkinsci/pipeline-utility-steps-plugin
