### ISSUE TITLE
Pipeline generator

### ISSUE THREAD

**Issue by mick-feller** [jenkinsci/git-changelog-plugin#19]
Hi,

your docs state that this plugin supports pipeline generator, but after install and restart of jenkins it's not showing up there?

Do you have any other form of documentation that i can use to get my pipeline going?

Thanks

**Comment by tomasbjerre** [comment]
It should show up as `gitChangelog` like this:
![screens-gc](https://user-images.githubusercontent.com/439571/39051216-47086c9a-44a8-11e8-91ce-e3f7745ffb44.png)

There are also examples in the readme that you can copy/paste to try it out.

**Comment by mick-feller** [comment]
![image](https://user-images.githubusercontent.com/32658692/39051311-45cb73ae-4476-11e8-8acc-001180f48e52.png)

I don't see it in my list :(

**Comment by tomasbjerre** [comment]
What version of the plugin?
What version of Jenkins?

**Comment by mick-feller** [comment]
nevermind, somehow it installed version 1.57 and just now i got an update message to version 2.0 and now it's showing up.

Thanks for your quick response!

**Comment by tomasbjerre** [comment]
Np! Its a big change in 2.0 so happy to handle any issues early.
