### ISSUE TITLE
gitChangelog step not working with slaves

### ISSUE THREAD

**Issue by akuzmenkovs** [jenkinsci/git-changelog-plugin#20]
Hi,

Newest gitChangelog step is not working with slaves.
It searches git repository on master.
Providing "repo" also doesn't helps. With repo: pwd(), it goes to D:\home\jenkinsUser\workspace. Without repo goes to D:\jenkinsHome\.

 * Plugin version used - 2.0.0
 * Jenkins version used - 2.115
 * Expected result:
Find git repository on slave
 * Actual result:
Searches git repository on master.

**Comment by tomasbjerre** [comment]
I'll have a look later today. The old scripts should still work.

**Comment by akuzmenkovs** [comment]
@tomasbjerre Yes, the old script is still working :)

**Comment by tomasbjerre** [comment]
Releasing 2.1 now. Will be available in update sites within a few hours.

**Comment by tomasbjerre** [comment]
Closing it now, but open it again if it is not working!
