### ISSUE TITLE
Cannot get the GITCHANGELOGJIRA macro to work

### ISSUE THREAD

**Issue by O5ten** [jenkinsci/git-changelog-plugin#25]
Plugin version used.
Jenkins version: 2.121.3

The job in question publishes JIRA Filter as a second to last step. 

Unable to pickup `${GITCHANGELOGJIRA}` variable from the Confluence Publisher Plugin that comes right after in our build configuration. Other build environment variables and macros are used in the Confluence Publisher and expanded properly. Am i doing something wrong or is the TOKEN never exported to the build?

**Comment by O5ten** [comment]
Plugin version: 2.7

**Comment by tomasbjerre** [comment]
You are not providing your configuration. It sounds like you are not using a pipeline. If not using pipeline this plugin adds 3 post build actions: "**Git Changelog**", **"Publish Jira filter"** and "**Publish Git Changelog**". Which one do you use?

**Comment by O5ten** [comment]
Correct, not using pipeline. 
I don't use Git Changelog or Publish Git Changelog, i only use the Publish JIRA Filter, 
but even when i do it does not expand the variable.

**Comment by O5ten** [comment]
![image](https://user-images.githubusercontent.com/3242379/45431103-39c7f700-b6a7-11e8-912c-26a65f41dec7.png)

Here's the configuration, not much else to it.

**Comment by tomasbjerre** [comment]
Ok. This plugin is a merge of 2 plugins and that part is maintained by @paulwellnerbou . I just do "**Git Changelog**". Assigning it to him.

**Comment by tomasbjerre** [comment]
As of 3.0 this action is not available anymore. See https://github.com/jenkinsci/git-changelog-plugin/pull/47 and discussion in https://github.com/jenkinsci/git-changelog-plugin/issues/41
