### ISSUE TITLE
Using Context in scripted pipeline requires script security approvals

### ISSUE THREAD

**Issue by rdicroce** [jenkinsci/git-changelog-plugin#27]
When using this plugin with returnType CONTEXT in a scripted pipeline, every model method has to be approved in the Script Security plugin. Otherwise, you get errors like:

> Scripts not permitted to use method se.bjurr.gitchangelog.api.model.interfaces.ICommits getCommits. Administrators can decide whether to approve or reject this signature.

IMO all of the model methods should be whitelisted so manually approving them is not necessary,

Jenkins version: 2.141
Git Changelog plugin version: 2.9
Script Security plugin version: 1.46

**Comment by tomasbjerre** [comment]
Sounds good.

Should be possible with something [like this](https://github.com/jenkinsci/simple-build-for-pipeline-plugin/blob/master/src/main/java/org/jenkinsci/plugins/simplebuild/SimpleBuildDSL.java).

**Comment by tomasbjerre** [comment]
Should be fixed in 2.10. Open issue again if not working.
