### ISSUE TITLE
Missing Pull Request Merges in Git Changelog

### ISSUE THREAD

**Issue by emoshaya** [jenkinsci/git-changelog-plugin#3]
The "Git Changelog" Publish Action works great in listing commits in the Jenkins Build Summary. However, it fails to list any of the Pull Request merges. Please see screenshots below of Actual Github Commits and the Jenkins Summary Page missing all the PR merges.

![github_commits](https://cloud.githubusercontent.com/assets/8818542/15010323/4e6e9166-11e3-11e6-807b-6c805c810620.png)

![jenkins_changelog](https://cloud.githubusercontent.com/assets/8818542/15010324/502f2d80-11e3-11e6-8755-10efd54790b7.png)

**Comment by tomasbjerre** [comment]
How have you configured the plugin?
Den 4 maj 2016 12:22 skrev "Paul Wellner Bou" notifications@github.com:

**Comment by emoshaya** [comment]
@tomasbjerre clearly from the screenshot I provided with the issue, the plugin is configured correctly as the commits are displayed in the Jenkins Build page but missing the PR Merges...Nevertheless, below are screenshots of the config..

![config-1](https://cloud.githubusercontent.com/assets/8818542/15011878/35340484-11ec-11e6-90fc-35de9869cd8f.png)
![config-2](https://cloud.githubusercontent.com/assets/8818542/15011883/37ac7020-11ec-11e6-9810-0c6dd38796e8.png)
![config-3](https://cloud.githubusercontent.com/assets/8818542/15011885/3a5b7d52-11ec-11e6-9eda-18df479116a5.png)
![config-4](https://cloud.githubusercontent.com/assets/8818542/15011890/3eb2c176-11ec-11e6-85e5-24b77a93169a.png)

**Comment by tomasbjerre** [comment]
You have pattern `^Merge.*`, remove that and it should work.

**Comment by emoshaya** [comment]
@tomasbjerre now I feel stupid. Thank you that worked!

**Comment by tomasbjerre** [comment]
No problem =) Perhaps its a bad default configuration. If more people wants to include merges, I'll change it.
