### ISSUE TITLE
Pipeline with render template when returning Context

### ISSUE THREAD

**Issue by crisp2u** [jenkinsci/git-changelog-plugin#33]
Environment:

- Jenkins ver. 2.150.1
- Plugin verstion 2.16

When running a pipeline I'm interested if it's possible to run the gitChangelog Step and return context object but then use a Mustache template to render a string.

I know that the library behind the plugin has the builder object but i'm not sure if and how I should use it directly.  The plugin step seems to do an abstraction of builder but I don't know if I can use it in my case.

Thanks

**Comment by tomasbjerre** [comment]
The context object is just a POJO so perhaps you can find some way of doing
that.

An alternative might be to just use groovy to construct a string from the
context. See
http://docs.groovy-lang.org/docs/next/html/documentation/template-engines.html


Den ons 6 mars 2019 17:25Cristian Pop <notifications@github.com> skrev:
