### ISSUE TITLE
please fix needed JAXB dependency for openjdk11

### ISSUE THREAD

**Issue by blka** [jenkinsci/git-changelog-plugin#34]
Environment:

Jenkins ver. 2.176
Plugin verstion 2.16

`java --version
openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7-LTS, mixed mode, sharing)`

it's because java 11 droped "java.xml.bind", right now it's impossible to use "--add-modules java.xml.bind"

this can be fixed by adding neccessary dependency JAXB from jenkins:
[JAXB-Plugin](https://wiki.jenkins.io/display/JENKINS/JAXB+Plugin)

Build log
`15:08:21 --- Git Changelog ---
15:08:21 ---
15:08:28 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
15:08:28 	at se.bjurr.gitchangelog.internal.integrations.rest.RestClient.withBasicAuthCredentials(RestClient.java:43)
15:08:28 	at se.bjurr.gitchangelog.internal.integrations.jira.DefaultJiraClient.withBasicCredentials(DefaultJiraClient.java:22)
15:08:28 	at se.bjurr.gitchangelog.internal.issues.IssueParser.createJiraClient(IssueParser.java:174)
15:08:28 	at se.bjurr.gitchangelog.internal.issues.IssueParser.parseForIssues(IssueParser.java:60)
15:08:28 	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:456)
15:08:28 	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:77)
15:08:28 	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:99)
15:08:28 	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
15:08:28 	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:148)
15:08:28 	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:26)
15:08:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
15:08:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
15:08:28 	at hudson.remoting.Request$2.run(Request.java:369)
15:08:28 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
15:08:28 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
15:08:28 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
15:08:28 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
15:08:28 	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by tomasbjerre** [comment]
Corrected and released in 2.17. Thanks for reporting!

**Comment by paulwellnerbou** [comment]
Thanks for the report,  @blka.

I started working on it. I did not touch the project for a long time, and I get tons of compile errors with the new jenkins and java versions, will have to consolidate the dependencies somehow.

Pull request from your side would be welcome ;-)
