### ISSUE TITLE
Build log exposes Jira credentials which was not the case in previous version.

### ISSUE THREAD

**Issue by anigetsin** [jenkinsci/git-changelog-plugin#38]
* Plugin version used -> 2.20
 * Jenkins version used -> 2.190

**Comment by tomasbjerre** [comment]
When using pipeline?
I will probably investigate and fix it tomorrow.

**Comment by anigetsin** [comment]
I am not using pipeline , its a free style job where I am just creating changelog file.

Check the image of the setttigs I have enabled, once I run the job then on build-log it gives away my secured password credentials.

![image](https://user-images.githubusercontent.com/47367361/68411031-bba29b80-0157-11ea-9ee3-419ff093a2d2.png)

**Comment by tomasbjerre** [comment]
Released in 2.21. Thanks for reporting!!

**Comment by anigetsin** [comment]
Thanks for quick workaround.
