### ISSUE TITLE
How to handle multiple issues in one commit message ?

### ISSUE THREAD

**Issue by igorek9191** [jenkinsci/git-changelog-plugin#39]
I'm using Jenkins Changelog plugin, which also uses our Jira. I've determined the Jira issue pattern like this one:  (WHIM-\d{4}) 
But the problem is that there are could be multiple Jira issues in one commit. How to handle all of them in a changelog template ?
I guess that in {{#issues}} section of template there should be some foreach loop to get every issue from a commit? Am I correct ? If yes then how to implement it ?

**Comment by tomasbjerre** [comment]
The context structure, what the issues variable contains, is described here:
https://github.com/tomasbjerre/git-changelog-lib

You can also let the plugin just return CONTEXT as described in the readme here. And construct the changelog howe er you want with groovy.
