### ISSUE TITLE
Old commits being shown in the ChangeLog

### ISSUE THREAD

**Issue by kiran009** [jenkinsci/git-changelog-plugin#43]
When reporting a bug, please try to provide as much information as possible.

 * Plugin version used. -- 
 * Jenkins version used -- 2.176.3
 * Your configuration:
   * Template and any other relevant details.
 * Expected result and actual result.
 * Any information from the logs:
   * Jenkins log: http://jenkins-server/log/
   * Build log.

**Comment by tomasbjerre** [comment]
Impossible to investigate because no information is provided.
