### ISSUE TITLE
Jira Summary is not fetched

### ISSUE THREAD

**Issue by TitliBasu37** [jenkinsci/git-changelog-plugin#49]
I am using below code :
        {
            def changelogString = gitChangelog returnType: 'STRING',
                from: [type: 'REF', value: "${currentReleaseTag}"],
                    to: [type: 'REF', value: 'master'],
                      ignoreCommitsIfMessageMatches: '^Merge.',
                      ignoreCommitsWithoutIssue: 'true',
                     jira: [issuePattern: 'CICD'+ '-([0-9]+)\\b',password: "${PASSWORD}", server: 'https://jira.com', username: "${USERNAME}"],  
               template: """
               
               <!DOCTYPE html>
<html lang="en">
<head>
<title>Change Log</title>
<style>
h2 {
  text-decoration: underline;
}
table {
  border: 1px solid black;
  border-collapse: collapse;
  width: 100%;
}
th, td {
  border: 1px solid black;
  border-collapse: collapse;
  text-align: left;
  padding: 8px;
}
tr:nth-child(even){background-color: #f2f2f2}
th {
  background-color: #0099cc;
  color: white;
}
</style>  
</head>
<p>
<div align="center">
 <h1><u>Change Log for {{repoName}}</u></h1>
 </div>
</p>

<h3>JOB NAME: ${JOB_NAME} </h3>
<h3> BUILD ID: ${BUILD_ID} </h3>
<h3>GIT BRANCH:${GIT_BRANCH}</h3>

{{#tags}}
<h2> {{name}} </h2>

  <table style="width:100%">
  <tr>
  <th>JIRA ID</th>
  <th>JIRA TITLE</th>
  <th>GIT MERGES</th>
  </tr>
  
 {{#issues}}
  {{#hasIssue}}
   <tr>
   <td>
 <a href="https://jira.com/browse/{{issue}}">{{issue}}</a> 
   </td>
   <td>
### {{name}} {{issue}} {{title}} {{#hasIssueType}} *{{issueType}}* {{/hasIssueType}} {{#hasLabels}} {{#labels}} *{{.}}* {{/labels}} {{/hasLabels}}
   </td>
    <td>
   {{#commits}}
   {{{messageTitle}}}
   <br/> 
<a href="http://cd.senncom.com:7990/projects/WTC/repos/webtoolcloud/commits/{{hash}}">{{hash}}</a> {{authorName}} <i>{{commitTime}}</i>
 <p/>
      {{/commits}}
      </td>
      </tr>
    {{/hasIssue}}
    {{^hasIssue}}
    {{/hasIssue}}
  {{/issues}}
  
  </table>
  {{/tags}}

</html>

But still not able to print the summary in 2nd collumn

Expected result - the 2nd collum  should fetch the JIRA ticket summary tab with JIRA issue ticlet no
actual result -  JIRA DE-10234

**Comment by tomasbjerre** [comment]
Still not following issue template
