### ISSUE TITLE
Add support for getting changelog between two commit ids

### ISSUE THREAD

**Issue by Garagoth** [jenkinsci/git-changelog-plugin#5]
Providing a specific commit id (sha) results in ref not found error.
Could you please add support for this - it will integrate nicely with promoted builds plugin which provides commit ids as env variables.

**Comment by tomasbjerre** [comment]
What version are you using of the plugin? Do you have a stacktrace?

**Comment by Garagoth** [comment]
Hi,
1.26 on Jenkins 2.6
I am trying to pass git commit id as fromRef and toRef fields, which fails with message:

> FATAL: Ref 8e4c1c5a4cd5758e5640e430ce40a077855e525a not found.
> java.lang.RuntimeException: Ref 8e4c1c5a4cd5758e5640e430ce40a077855e525a not found.
>     at de.wellnerbou.gitchangelog.jgit.GitLogBetween.getJGitLogBetween(GitLogBetween.java:38)
>     at de.wellnerbou.gitchangelog.jgit.GitLogBetween.getGitLogBetween(GitLogBetween.java:25)
>     at de.wellnerbou.gitchangelog.app.GitChangelog.changelog(GitChangelog.java:83)
>     at de.wellnerbou.jenkins.gitchangelog.callable.GitChangelogMasterToSlaveCallable.call(GitChangelogMasterToSlaveCallable.java:24)
>     at de.wellnerbou.jenkins.gitchangelog.callable.GitChangelogMasterToSlaveCallable.call(GitChangelogMasterToSlaveCallable.java:14)
>     at hudson.FilePath.act(FilePath.java:1105)
>     at de.wellnerbou.jenkins.gitchangelog.publish.GitLogGenericPostPublishPerformer.perform(GitLogGenericPostPublishPerformer.java:37)
>     at de.wellnerbou.jenkins.gitchangelog.publish.GitLogJiraFilterPostPublisher.perform(GitLogJiraFilterPostPublisher.java:49)
>     at hudson.plugins.promoted_builds.Promotion$RunnerImpl.build(Promotion.java:403)
>     at hudson.plugins.promoted_builds.Promotion$RunnerImpl.doRun(Promotion.java:345)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
>     at hudson.model.Run.execute(Run.java:1741)
>     at hudson.model.Run.run(Run.java:1679)
>     at hudson.plugins.promoted_builds.Promotion.run(Promotion.java:284)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)

**Comment by tomasbjerre** [comment]
Stacktrace shows you are using @paulwellnerbou part of the plugin. I'm assigning to him.

**Comment by paulwellnerbou** [comment]
@Garagoth, sorry for the late reply. Actually this should work. I will have a look into it and report back.

**Comment by paulwellnerbou** [comment]
Fixed with 1.28.

**Comment by paulwellnerbou** [comment]
Fixed with 1.28.
