### ISSUE TITLE
{{title}} is not working

### ISSUE THREAD

**Issue by TitliBasu37** [jenkinsci/git-changelog-plugin#50]
Plugin version used: 2.10
Jenkins version used: 2.141
Your configuration:
                 def previousReleaseVersion = getCurrentReleaseVersion(RELEASE)
                   def currentReleaseTag = "${RELEASE}/" + previousReleaseVersion
                   print "Current Release tag: ${currentReleaseTag}"
             withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: '*****',
            usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']])
                  {
            def changelogString = gitChangelog returnType: 'STRING',
                from: [type: 'REF', value: "${currentReleaseTag}"],
                    to: [type: 'REF', value: 'master'],
                      ignoreCommitsIfMessageMatches: '^Merge.',
                      ignoreCommitsWithoutIssue: 'true',
                     jira: [issuePattern: 'CICD'+ '-([0-9]+)\\b',password: "${PASSWORD}", server: 'https://jira.com', username: "${USERNAME}"],  
               template: """
               
               <!DOCTYPE html>
<html lang="en">
<head>
<title>Change Log</title>
<style>
h2 {
  text-decoration: underline;
}
table {
  border: 1px solid black;
  border-collapse: collapse;
  width: 100%;
}
th, td {
  border: 1px solid black;
  border-collapse: collapse;
  text-align: left;
  padding: 8px;
}
tr:nth-child(even){background-color: #f2f2f2}
th {
  background-color: #0099cc;
  color: white;
}
</style>  
</head>
<p>
<div align="center">
 <h1><u>Change Log for {{repoName}}</u></h1>
 </div>
</p>

<h3>JOB NAME: ${JOB_NAME} </h3>
<h3> BUILD ID: ${BUILD_ID} </h3>
<h3>GIT BRANCH:${GIT_BRANCH}</h3>

{{#tags}}
<h2> {{name}} </h2>

  <table style="width:100%">
  <tr>
  <th>JIRA ID</th>
  <th>JIRA TITLE</th>
  <th>GIT MERGES</th>
  </tr>
  
 {{#issues}}
  {{#hasIssue}}
   <tr>
   <td>
 <a href="https://jira.com/browse/{{issue}}">{{issue}}</a> 
   </td>
   <td>
 {{title}} 
   </td>
    <td>
   {{#commits}}
   {{{messageTitle}}}
   <br/> 
<a href="http://clink/commits/{{hash}}">{{hash}}</a> {{authorName}} <i>{{commitTime}}</i>
 <p/>
      {{/commits}}
      </td>
      </tr>
    {{/hasIssue}}
    {{^hasIssue}}
    {{/hasIssue}}
  {{/issues}}
  
  </table>
  {{/tags}}

</html>
"""

Expected result and actual result.
Expected :  the 2nd collum should fetch the JIRA ticket summary tab with JIRA issue ticlet no
Actual :  blank
{{title}} is not working

Any information from the logs:  There is no error in logs 👍 

Masking supported pattern matches of %USERNAME% or %PASSWORD%
[Pipeline] {
[Pipeline] gitChangelog
[Pipeline] writeFile
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // script

**Comment by tomasbjerre** [comment]
Try version 3.0 of plugin.
Try using  jira api token.
Check both build log and jenkins global log.

This is likely a problem with integration with jira.

**Comment by TitliBasu37** [comment]
As a {{title}} exactly what should come in the  output from a Jira ticket page ?

**Comment by tomasbjerre** [comment]
This: 
https://github.com/tomasbjerre/git-changelog-lib/blob/8596ffa8173a4c537140c21860530e967965f69c/src/main/java/se/bjurr/gitchangelog/internal/integrations/jira/JiraClient.java#L37

And jira response looks like:
https://github.com/tomasbjerre/git-changelog-lib/blob/8596ffa8173a4c537140c21860530e967965f69c/src/test/resources/jira-issue-jir-1234.json#L7

**Comment by TitliBasu37** [comment]
Thanks will try ...do u have any example using the plugin with  jira api token

**Comment by tomasbjerre** [comment]
Try the snippet generator:
https://www.jenkins.io/doc/book/pipeline/getting-started/#snippet-generator

Den mån 10 aug. 2020 14:332018201920201920 <notifications@github.com> skrev:

**Comment by TitliBasu37** [comment]
I tried upgrading the plugin version to 3.0....but still no luck...{{title}} field is coming blank :(

**Comment by TitliBasu37** [comment]
In our project...they are saying jira api token is not allowed to create as it will burden the jiras for the rest api calls...anyway the jira ticketid hyperlink is opening...but still not jira  title is coming...any other way to populate the jira titles

**Comment by tomasbjerre** [comment]
That is expected when you do not supply cfedentials and this plugin will not be able to integrate with jira to get the title.

**Comment by TitliBasu37** [comment]
But I am supplying the credentials with class UsernamePasswordMultiBinding :


withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'CICD_Credential_ID',
            usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']])
                  {
            def changelogString = gitChangelog returnType: 'STRING',
                from: [type: 'REF', value: "${currentReleaseTag}"],
                    to: [type: 'REF', value: 'master'],
                      ignoreCommitsIfMessageMatches: '^Merge.',
                      ignoreCommitsWithoutIssue: 'true',
                     jira: [issuePattern: 'CICD'+ '-([0-9]+)\\b',password: "${PASSWORD}", server: 'https://jira.com', username: "${USERNAME}"],  

But still why the {{title}} is not getting printed though jira tickets are opening in the changelog.html

**Comment by TitliBasu37** [comment]
Working thanks a lot

**Comment by sprnza** [comment]
Hey @TitliBasu37 I've faced the same issue. Could you possibly recall how had you managed to solve the issue?

**Comment by AndreasScharfCPB** [comment]
Hu @TitliBasu37  How is this working now? 
I have got the same issue. I cannot get Jira issue title. Cannot find any information in the logs.
I am using hardcoded username and password for now to rule out any problems there.
Did you change anything in your Jenkins script? The Jira URL maybe?
