### ISSUE TITLE
Pipeline snippet generator is broken in newer Jenkins versions

### ISSUE THREAD

**Issue by chrisipa** [jenkinsci/git-changelog-plugin#53]
Hi,

it seems like the pipeline snippet generator for the plugin is broken in newer Jenkins LTS versions. We are currently using:
- Jenkins LTS 2.249.2
- Plugin version 3.0

Here's a log file with the exception from the Jenkins standard out:
- [git-changelog-exception-log.txt](https://github.com/jenkinsci/git-changelog-plugin/files/5446249/git-changelog-exception-log.txt)

Best regards
Chris

**Comment by tomasbjerre** [comment]
It works in `2.243` but not in any version from `2.244`.

https://github.com/jenkinsci/jenkins/compare/jenkins-2.243...jenkins-2.244

**Comment by tomasbjerre** [comment]
I created https://issues.jenkins-ci.org/browse/JENKINS-64071

**Comment by chrisipa** [comment]
Thank you very much. Please keep me posted.

**Comment by tomasbjerre** [comment]
It works with 2.264. I will close this issue and refer to the Jenkins Jira ticket:
https://issues.jenkins-ci.org/browse/JENKINS-64071
