### ISSUE TITLE
ParseException: Unexpected End Of File

### ISSUE THREAD

**Issue by thomas-eaa** [jenkinsci/git-changelog-plugin#59]
Hi,

At least since 3.5 we encounter the following error message with most repositories:

net.minidev.json.parser.ParseException: Unexpected End Of File position <xxx>: null

A downgrade to 3.2 resolved the issue. Didn't try with versions 3.3 and 3.4 that might also work.

Thank you!

**Comment by tomasbjerre** [comment]
You must supply your configuration, or else this is impossible to work with.
