### ISSUE TITLE
Intermittent failures JSON parsing - the issue is not reproduced when same job rebuilt after some time.

### ISSUE THREAD

**Issue by avivek** [jenkinsci/git-changelog-plugin#62]
Recently the git change log plugin starts failing intermittently with the following error stack:

net.minidev.json.parser.ParseException: Unexpected End Of File position 2251: null
19:49:28  	at net.minidev.json.parser.JSONParserMemory.readString(JSONParserMemory.java:122)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:410)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:546)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:403)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:546)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:403)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:546)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:403)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:546)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:403)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readArray(JSONParserBase.java:273)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:406)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:546)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readMain(JSONParserBase.java:403)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:546)
19:49:28  	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:301)
19:49:28  	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:158)
19:49:28  	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
19:49:28  	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:271)
19:49:28  	at com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.parse(JsonSmartJsonProvider.java:62)
19:49:28  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to EC2 (Jenkins-Slaves) - jenkins-slave(docker compose) (i-0af49e7a4434d79df)
19:49:28  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
19:49:28  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
19:49:28  		at hudson.remoting.Channel.call(Channel.java:1001)
19:49:28  		at hudson.FilePath.act(FilePath.java:1249)
19:49:28  		at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep$1.run(GitChangelogStep.java:358)
19:49:28  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
19:49:28  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
19:49:28  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:49:28  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
19:49:28  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
19:49:28  		at java.base/java.lang.Thread.run(Thread.java:829)
19:49:28  Caused: com.jayway.jsonpath.InvalidJsonException
19:49:28  	at com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.parse(JsonSmartJsonProvider.java:64)
19:49:28  	at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:37)
19:49:28  	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:498)
19:49:28  	at se.bjurr.gitchangelog.internal.integrations.jira.JiraClient.toJiraIssue(JiraClient.java:38)
19:49:28  	at se.bjurr.gitchangelog.internal.integrations.jira.DefaultJiraClient.getIssue(DefaultJiraClient.java:40)
19:49:28  	at se.bjurr.gitchangelog.internal.issues.IssueParser.createParsedIssue(IssueParser.java:225)
19:49:28  	at se.bjurr.gitchangelog.internal.issues.IssueParser.parseForIssues(IssueParser.java:82)
19:49:28  	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:585)
19:49:28  	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:83)
19:49:28  	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:109)
19:49:28  	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:140)
19:49:28  	at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep.perform(GitChangelogStep.java:452)
19:49:28  	at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep.access$000(GitChangelogStep.java:45)
19:49:28  	at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep$1$1.call(GitChangelogStep.java:354)
19:49:28  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
19:49:28  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
19:49:28  	at hudson.remoting.Request$2.run(Request.java:376)
19:49:28  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
19:49:28  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:49:28  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
19:49:28  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
19:49:28  	at java.base/java.lang.Thread.run(Thread.java:834)

The issue does not recur when rebuilt later on a new machine.

**Comment by tomasbjerre** [comment]
Try version 3.9. Follow issue template if you want to open an issue.
