### ISSUE TITLE
How to get changelog between HEAD and most recent tag?

### ISSUE THREAD

**Issue by webminster** [jenkinsci/git-changelog-plugin#66]
### Describe your use-case which is not covered by existing documentation.

Is there any way to get the changes between the top of the repor (HEAD) and the most recent of some matching tag?   I need to create a changelog for what changed between HEAD and the last "release" that was done.

I'm trying to use the pipeline version of this, but I see no options for this in the snippets generator.   As far as tag refs, all I see is a fixed reference to 'git-changelog-1.50', but no other samples.

Can you explain tag refs a little better?  Thanks.

**Comment by tomasbjerre** [comment]
Update to version 3.19 and that feature should be available. Documented in readme here:
https://github.com/jenkinsci/git-changelog-plugin#determine-highest-version-from-commit-messages
Open issue again if any problems.

**Comment by webminster** [comment]
Sorry, but how does this change help?  I am trying to get a changelog between tags.  This change appears to be how to get a version number.  Can you explain?
