### ISSUE TITLE
Pipeline and job-dsl compatibility

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/git-changelog-plugin#7]
Make sure it works with the pipeline plugin and can be configured with job-dsl. Also document this in the   readme.

**Comment by Mc-Mido** [comment]
Can we use git-changelog-plugin in a Jenkins pipeline? Please could you update the readme file with a how to use this plugin into a pipeline?

**Comment by tomasbjerre** [comment]
Yes. It should be possible. You should be able to autogenerate the config.

https://jenkins.url/pipeline-syntax/html

Where jenkins.url is the base URL of your Jenkins server.

**Comment by Mc-Mido** [comment]
I didn't see GitChangelogRecorder...

Ty for your quick answer.
